// ─── ASSET CONFIGURATION ─────────────────────────────────────
export const PLAYER_SPACESHIP_SRC = 'assets/images/player.png';
export const ALIEN_ENEMY_SRC = 'assets/images/alien.png';
export const LUCKY_BOX_SRC = 'assets/images/luckybox.png';
export const HEART_SRC = 'assets/images/heart.png';

// Preload images only if paths are provided
export const IMAGES = {};
export function preloadImage(key, src) {
  if (!src) return;
  const img = new Image();
  img.src = src;
  img.onload = () => { IMAGES[key] = img; };
}
preloadImage('player', PLAYER_SPACESHIP_SRC);
preloadImage('alien', ALIEN_ENEMY_SRC);
preloadImage('lucky', LUCKY_BOX_SRC);
preloadImage('heart', HEART_SRC);

// ─── WORD BANKS (scaled by difficulty, per language) ─────────
export const WORD_BANKS_EN = {
  easy: [
    'ace', 'arm', 'bat', 'box', 'bug', 'cap', 'cow', 'cup', 'dew', 'dig',
    'dot', 'dug', 'elk', 'end', 'fan', 'fig', 'fog', 'fun', 'gap', 'gem',
    'gum', 'gut', 'hat', 'hex', 'hop', 'hub', 'ice', 'imp', 'ink', 'ion',
    'ivy', 'jam', 'jar', 'jaw', 'jet', 'jig', 'jot', 'joy', 'jug', 'keg',
    'key', 'kid', 'kit', 'lab', 'lap', 'law', 'leg', 'lid', 'lip', 'log',
    'lot', 'lug', 'map', 'mat', 'mix', 'mob', 'mop', 'mud', 'mug', 'nap',
    'net', 'nil', 'nod', 'nor', 'nut', 'oak', 'odd', 'oil', 'opt', 'orb',
    'ore', 'owl', 'pad', 'paw', 'peg', 'pen', 'pig', 'pin', 'pit', 'pod',
    'pot', 'pub', 'pun', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw', 'red',
    'rib', 'rid', 'rim', 'rip', 'rod', 'rot', 'row', 'rug', 'rum', 'run',
    'rut', 'sap', 'sat', 'saw', 'set', 'sin', 'sip', 'sit', 'six', 'ski',
    'sob', 'sod', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax',
    'ten', 'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'top', 'tow', 'toy',
    'tub', 'tug', 'two', 'urn', 'van', 'vat', 'vet', 'vow', 'wag', 'war',
    'wax', 'web', 'wig', 'win', 'wit', 'wok', 'won', 'wry', 'yak', 'yam',
    'yap', 'yaw', 'yep', 'yet', 'yew', 'zip', 'zoo',
  ],
  medium: [
    'alpha', 'amber', 'anvil', 'armor', 'atlas', 'azure', 'basin', 'blast',
    'blaze', 'blink', 'bloom', 'brain', 'brave', 'brick', 'brisk', 'cable',
    'candy', 'cedar', 'chain', 'charm', 'chess', 'chill', 'china', 'civic',
    'claim', 'clash', 'clear', 'cliff', 'climb', 'cloud', 'cobra', 'comet',
    'coral', 'craft', 'crane', 'crash', 'crest', 'crown', 'crush', 'cubic',
    'curve', 'dance', 'debug', 'delta', 'depth', 'disco', 'draft', 'drain',
    'dream', 'drift', 'drone', 'dwarf', 'eagle', 'earth', 'elder', 'ember',
    'enact', 'epoch', 'equal', 'equip', 'erupt', 'event', 'exile', 'expat',
    'extra', 'fable', 'feast', 'fiber', 'flame', 'flare', 'flash', 'fleet',
    'flint', 'float', 'flora', 'fluid', 'forge', 'forth', 'frost', 'gleam',
    'globe', 'gloom', 'glyph', 'grain', 'grape', 'grasp', 'grind', 'guild',
    'haven', 'hazel', 'helix', 'honor', 'hover', 'humid', 'hyper', 'ivory',
    'jewel', 'joust', 'knack', 'kneel', 'kraft', 'lance', 'laser', 'latch',
    'layer', 'level', 'light', 'llama', 'lodge', 'logic', 'lunar', 'lyric',
    'magic', 'manor', 'maple', 'marsh', 'medal', 'mercy', 'metal', 'micro',
    'mimic', 'minor', 'mocha', 'model', 'moral', 'mount', 'music', 'nerve',
    'noble', 'north', 'novel', 'ocean', 'omega', 'onset', 'opera', 'optic',
    'orbit', 'oxide', 'ozone', 'panic', 'patch', 'pearl', 'phase', 'piano',
    'pilot', 'pixel', 'plank', 'plant', 'plaza', 'plumb', 'plume', 'polar',
    'power', 'prawn', 'pride', 'prime', 'print', 'prism', 'prize', 'probe',
    'proof', 'prose', 'proxy', 'pulse', 'quake', 'query', 'quest', 'quick',
    'quota', 'radar', 'rapid', 'raven', 'realm', 'reign', 'relay', 'ridge',
    'rival', 'robin', 'royal', 'rumba', 'saber', 'saint', 'salsa', 'scale',
    'scout', 'serif', 'shark', 'shelf', 'shift', 'sigma', 'sleek', 'slice',
    'slope', 'smart', 'smoke', 'snake', 'snare', 'solar', 'sonic', 'south',
    'space', 'spark', 'spawn', 'spear', 'spice', 'spike', 'spine', 'spoke',
    'squad', 'stack', 'staff', 'stage', 'stain', 'stake', 'stale', 'stamp',
    'stand', 'stark', 'steam', 'steel', 'steep', 'steer', 'stern', 'still',
    'stock', 'stoic', 'stone', 'storm', 'stout', 'stove', 'strap', 'straw',
    'strip', 'stump', 'super', 'surge', 'swamp', 'sweep', 'swift', 'sword',
    'talon', 'tempo', 'tiger', 'token', 'topaz', 'total', 'tower', 'trace',
    'track', 'trade', 'trail', 'train', 'trait', 'trend', 'triad', 'trial',
    'trick', 'trine', 'troop', 'truce', 'trunk', 'trust', 'tulip', 'turbo',
    'tweed', 'twist', 'ultra', 'umbra', 'unify', 'unity', 'until', 'upper',
    'urban', 'usher', 'utter', 'vague', 'valve', 'vault', 'vigor', 'vinyl',
    'viper', 'virus', 'visor', 'vista', 'vital', 'vivid', 'vocal', 'voice',
    'voter', 'vowel', 'watch', 'water', 'wheat', 'whirl', 'wield', 'witch',
    'world', 'wound', 'wrath', 'yacht', 'yield', 'youth', 'zebra', 'zonal',
  ],
  hard: [
    'alchemy', 'android', 'anomaly', 'apostle', 'archive', 'arsenal',
    'balance', 'banshee', 'battery', 'beacon', 'blanket', 'blazing',
    'blister', 'booster', 'capsule', 'cardiac', 'cascade', 'celsius',
    'chamber', 'channel', 'chapter', 'chariot', 'chimera', 'circuit',
    'cluster', 'coaster', 'cockpit', 'compile', 'complex', 'console',
    'contest', 'control', 'convert', 'crystal', 'current', 'crusade',
    'cyclone', 'datalog', 'decibel', 'decrypt', 'defense', 'destiny',
    'diamond', 'digital', 'discord', 'display', 'distort', 'dolphin',
    'dynasty', 'eclipse', 'element', 'embargo', 'encrypt', 'entropy',
    'episode', 'erosion', 'exploit', 'extract', 'falafel', 'fallout',
    'fantasy', 'fiction', 'firefly', 'fission', 'flannel', 'flexion',
    'formula', 'fortune', 'freight', 'furnace', 'gadget', 'galahad',
    'gateway', 'genesis', 'glacier', 'granite', 'gravity', 'griffin',
    'habitat', 'halcyon', 'handoff', 'harmony', 'harvest', 'heretic',
    'hexagon', 'holster', 'horizon', 'hostile', 'hydrant', 'hypnotic',
    'iceberg', 'igniter', 'illusion', 'imaging', 'implant', 'impulse',
    'inferno', 'insight', 'install', 'ionizer', 'javelin', 'jigsaw',
    'journal', 'jubilee', 'justice', 'ketchup', 'kingdom', 'kinetic',
    'kitchen', 'lantern', 'lattice', 'leather', 'liberty', 'lighten',
    'lockout', 'maestro', 'magnate', 'mandala', 'martial', 'masking',
    'maximum', 'mercury', 'militia', 'mineral', 'mission', 'mixture',
    'modular', 'monitor', 'monsoon', 'monster', 'morning', 'mystery',
    'nebula', 'neptune', 'network', 'neutron', 'nitrate', 'nuclear',
    'nucleus', 'nullify', 'obelisk', 'obscure', 'optimal', 'organic',
    'origami', 'outpost', 'overdub', 'ovation', 'oxidize', 'package',
    'paddock', 'paradox', 'passage', 'patriot', 'payload', 'penalty',
    'pension', 'peptide', 'phantom', 'pilgrim', 'planner', 'plastic',
    'platoon', 'plunder', 'polygon', 'popcorn', 'precept', 'presage',
    'problem', 'procure', 'prodigy', 'profile', 'project', 'protect',
    'protest', 'protons', 'provoke', 'pyramid', 'quantum', 'quarrel',
    'radical', 'rampart', 'reactor', 'rebound', 'recital', 'refract',
    'refugee', 'remnant', 'require', 'resolve', 'revolve', 'ripcord',
    'runtime', 'rupture', 'salvage', 'scandal', 'scarlet', 'scatter',
    'scourge', 'segment', 'shelter', 'shuttle', 'silicon', 'sinuous',
    'skeptic', 'society', 'solvent', 'species', 'stadium', 'stealth',
    'storage', 'stratum', 'subject', 'subsidy', 'sunrise', 'surplus',
    'suspend', 'symbiont', 'synapse', 'tabloid', 'takeoff', 'tempest',
    'theorem', 'therapy', 'thermal', 'thunder', 'topiary', 'torpedo',
    'torsion', 'tracker', 'trading', 'transit', 'trigger', 'tropics',
    'tsunami', 'turbine', 'tweaker', 'twister', 'unicorn', 'uniform',
    'unleash', 'uranium', 'utility', 'vaccine', 'vagrant', 'vanguard',
    'venture', 'verdict', 'version', 'vertigo', 'veteran', 'villain',
    'vintage', 'voltage', 'vortex', 'vulture', 'warhead', 'warrior',
    'whisker', 'whistle', 'widgeon', 'wildcat', 'witness', 'wrangle',
    'xchange', 'yielded', 'zealous', 'zephyr', 'zenith',
  ],
  expert: [
    'absolute', 'abstract', 'accuracy', 'advanced', 'advisory',
    'advocate', 'aircraft', 'alchemic', 'alliance', 'almanack',
    'ambiance', 'amusedly', 'analysis', 'ancestor', 'antidote',
    'aperture', 'aquarium', 'artifice', 'assassin', 'backbone',
    'bacteria', 'ballroom', 'bankrupt', 'biomorph', 'blackout',
    'blizzard', 'boundary', 'bracelet', 'broadest', 'bulkhead',
    'calendar', 'campaign', 'capsicum', 'cardinal', 'catalyst',
    'category', 'cerebral', 'champion', 'chapters', 'checkbox',
    'chromium', 'claymore', 'cliffhanger', 'cockerel', 'collider',
    'comeback', 'compiler', 'compound', 'computer', 'concrete',
    'conquest', 'contract', 'controls', 'copyhold', 'corridor',
    'crossbow', 'crucible', 'cultural', 'currency', 'cyberpunk',
    'database', 'deadline', 'debugger', 'decimate', 'defender',
    'diagnose', 'dialogue', 'diplomat', 'discount', 'dispatch',
    'dividend', 'doctrine', 'document', 'dominant', 'dominion',
    'doorstep', 'download', 'dreadful', 'dropship', 'dynamite',
    'eclipsed', 'eighteen', 'electron', 'eloquent', 'embedded',
    'emigrant', 'emphatic', 'encoding', 'endpoint', 'enforced',
    'engulfed', 'enormous', 'envelope', 'equation', 'equipped',
    'espresso', 'eternity', 'evaluate', 'eventful', 'evidence',
    'exchange', 'excludes', 'exercise', 'expedite', 'explorer',
    'external', 'extremes', 'fabulous', 'facedown', 'failsafe',
    'familiar', 'fastball', 'featured', 'feedback', 'filename',
    'finalize', 'finished', 'firmware', 'flagship', 'flashgun',
    'flexible', 'folklore', 'footstep', 'forecast', 'forensic',
    'fragment', 'freefall', 'frequent', 'frontier', 'fullback',
    'function', 'futility', 'gatepost', 'genocide', 'gigabyte',
    'gladiola', 'globetrotter', 'glossary', 'graphene', 'greenery',
    'gridlock', 'guardian', 'guidance', 'gunsmith', 'gyratory',
    'halftime', 'handbook', 'handmade', 'handover', 'hardcore',
    'hardware', 'harmonic', 'headband', 'headline', 'helpline',
    'heritage', 'highrise', 'hologram', 'homeland', 'horseman',
    'hospital', 'humanoid', 'huntsman', 'hydrogen', 'hysteria',
    'icebound', 'ignition', 'illusive', 'imagined', 'immunity',
    'imperial', 'incident', 'indulged', 'industry', 'infrared',
    'inherent', 'injector', 'innocent', 'inscribe', 'insignia',
    'integral', 'interact', 'interior', 'interval', 'invasion',
    'invented', 'invoking', 'iodizing', 'isolated', 'issuing',
    'jailbird', 'jamboree', 'japanese', 'jettison', 'judgment',
    'junction', 'keepsake', 'keyboard', 'khaki', 'knockout',
    'labeling', 'lambchop', 'landmark', 'language', 'latitude',
    'lavender', 'layabout', 'leapfrog', 'leverage', 'licensed',
    'lifelong', 'ligature', 'limiting', 'linkable', 'literacy',
    'lockdown', 'longhand', 'luminous', 'magnetic', 'mainland',
    'majestic', 'manifest', 'maritime', 'mastered', 'matchbox',
    'maximise', 'mechanic', 'medicine', 'membrane', 'memorial',
    'merchant', 'metadata', 'milepost', 'minimize', 'minority',
    'modifier', 'moisture', 'molecule', 'momentum', 'monopoly',
    'monument', 'mortgage', 'multiply', 'mustache', 'mutation',
    'navigate', 'notebook', 'nucleus', 'numerous', 'obituary',
    'obligate', 'obstacle', 'occupied', 'offshoot', 'onscreen',
    'operated', 'opponent', 'opposing', 'optimise', 'optional',
    'organism', 'original', 'orthodox', 'outbreak', 'outreach',
    'overcome', 'overhead', 'overload', 'overlord', 'overtake',
    'paradigm', 'parallel', 'paranoid', 'particle', 'passport',
    'patience', 'peculiar', 'pendulum', 'pentagon', 'perceive',
    'persists', 'personal', 'petition', 'pipeline', 'platform',
    'playback', 'pleasure', 'polished', 'populist', 'portable',
    'position', 'positive', 'powerful', 'preclude', 'predator',
    'preserve', 'pressure', 'presumed', 'proceeds', 'producer',
    'profound', 'progress', 'prohibit', 'prologue', 'promptly',
    'properly', 'proposal', 'prospect', 'protocol', 'provider',
    'publicly', 'pullback', 'punitive', 'purchase', 'pursuant',
    'puzzling', 'quadrant', 'quantify', 'quantity', 'question',
    'quotient',
  ],
};

export const WORD_BANKS_ID = {
  easy: [
    'abu', 'ada', 'air', 'aku', 'api', 'apa', 'ara', 'asa', 'ban', 'bak',
    'bau', 'bab', 'bah', 'bel', 'bis', 'bom', 'bor', 'bos', 'bui', 'bun',
    'bus', 'cap', 'cat', 'dam', 'dan', 'dom', 'doa', 'dua', 'ego', 'era',
    'flu', 'gas', 'gel', 'gua', 'hak', 'hal', 'hai', 'hiu', 'iga',
    'ibu', 'ini', 'itu', 'jas', 'jam', 'jua', 'juz', 'jin', 'alu', 'jok',
    'jus', 'kap', 'kas', 'kah', 'kol', 'kok', 'kos', 'kek', 'kue', 'kur',
    'lah', 'lap', 'las', 'lem', 'les', 'lor', 'luk', 'mah', 'mau', 'mak',
    'mas', 'mat', 'mie', 'mur', 'nol', 'nya', 'oli', 'ons', 'pos', 'pak',
    'pen', 'pas', 'per', 'pes', 'pir', 'pon', 'pun', 'rak', 'ram', 'ras',
    'rel', 'rem', 'rim', 'rok', 'rit', 'roh', 'ruh', 'ria', 'rua', 'sah', 'sak',
    'sal', 'sap', 'sel', 'sen', 'sok', 'sup', 'sih', 'tam', 'teh', 'tik',
    'tim', 'tol', 'top', 'tua', 'tuk', 'ubi', 'uji', 'vas', 'wah', 'zat',
  ],
  medium: [
    'abjad', 'absen', 'acung', 'acuan', 'adegan', 'agama', 'ahli', 'hari',
    'ajaib', 'akrab', 'akbar', 'alami', 'ampuh', 'asing', 'ambil',
    'ancam', 'andal', 'angka', 'angin', 'antar', 'apung', 'aneka',
    'arwah', 'bakti', 'awasi', 'bakat', 'bakar', 'bambu', 'bantu',
    'baris', 'batas', 'batin', 'bayar', 'bedah', 'bekal', 'belah',
    'benar', 'berita', 'bijak', 'bilas', 'bisik', 'buang', 'buaya',
    'budak', 'bukit', 'bulat', 'bumbu', 'bunga', 'buruk', 'cabai',
    'cacat', 'cedok', 'cagar', 'calon', 'camat', 'catat', 'cekik',
    'celah', 'cepat', 'cipta', 'corak', 'cuaca', 'cubit', 'cocok',
    'curah', 'dahan', 'damai', 'debat', 'dekat', 'delta', 'demam',
    'derap', 'desas', 'dewan', 'didik', 'dinas', 'domba', 'dunia',
    'dusun', 'eksak', 'ember', 'emosi', 'empat', 'endap', 'emas',
    'elang', 'fajar', 'fatal', 'fauna', 'serat', 'sosok', 'akhir',
    'pohon', 'pusat', 'sekat', 'purba', 'gagas', 'galak', 'garuk',
    'gelar', 'gempa', 'genap', 'gerak', 'gigit', 'gosip', 'ampun',
    'habis', 'halal', 'harap', 'harga', 'hebat', 'hemat', 'hibah',
    'hijau', 'hilir', 'hutan', 'ideal', 'iklan', 'ilham', 'imaji',
    'indah', 'masuk', 'jahat', 'jarak', 'jatuh', 'jelas', 'jenis',
    'jeruk', 'jihad', 'jilid', 'juluk', 'jurus', 'kabar', 'kawat',
    'kacau', 'kadar', 'kadal', 'kalah', 'kamar', 'kasur', 'kecil',
    'kejar', 'keras', 'kilat', 'tagih', 'kobar', 'kopra', 'krisis',
    'kubis', 'kulit', 'kumis', 'kursi', 'lahan', 'lapar', 'layak',
    'lebah', 'lemah', 'licik', 'ujung', 'logam', 'lokal', 'lomba',
    'lunak', 'lunas', 'mahal', 'mahir', 'makan', 'makin', 'malah',
    'mandi', 'marak', 'marga', 'merah', 'milik', 'mimpi', 'mirip',
    'rudal', 'mobil', 'ragam', 'mogok', 'watak', 'karsa', 'mulia',
    'mulut', 'mulus', 'lukis', 'murni', 'nakal', 'napas', 'nasib',
    'nekat', 'nikah', 'nomor', 'norma', 'nanas', 'nyala', 'danau',
    'obral', 'tubuh', 'paham', 'paksa', 'panas', 'bilah', 'papan',
    'pasar', 'pecah', 'pedas', 'peluk', 'perak', 'pergi', 'pesan',
    'petak', 'pilar', 'polah', 'sehat', 'prosa', 'puasa', 'pucat',
    'lacak', 'rajin', 'rapat', 'redam', 'renang', 'resah', 'resmi',
    'robek', 'rahim', 'rubah', 'ruang', 'sabuk', 'nalar', 'sakit',
    'pundi', 'salut', 'samar', 'saraf', 'sebab', 'semak', 'sibuk',
    'siram', 'sisir', 'surya', 'sulit', 'sulur', 'surat', 'tabir',
    'tajam', 'taman', 'tanah', 'tapak', 'tekad', 'telur', 'tenar',
    'terka', 'tidak', 'tanda', 'timah', 'tinta', 'tokoh', 'topan',
    'tujuh', 'bisul', 'tunas', 'tusuk', 'udara', 'ukiran', 'ulang',
    'ulama', 'utama', 'tukar', 'kuman', 'suara', 'wajah', 'warna',
    'wasit', 'yakni', 'yakin', 'iuran', 'zakar', 'zaman', 'satwa',
  ],
  hard: [
    'mutlak', 'ginjal', 'tangkas', 'kerani', 'alamiah', 'biduran',
    'amanat', 'anggrek', 'ganjil', 'ramuan', 'perajin', 'idaman',
    'kapang', 'bandara', 'barokah', 'berlian', 'bijaksana', 'bintang',
    'bongkar', 'tanaman', 'budiman', 'cakrawala', 'catatan', 'cendana',
    'centang', 'cerdas', 'ciptaan', 'dampak', 'daratan', 'peminjam',
    'batasan', 'pelapukan', 'dermaga', 'dewata', 'wangsa', 'ijazah',
    'tertib', 'senyap', 'semesta', 'dagang', 'galian', 'listrik',
    'bukti', 'setempat', 'wabah', 'pajangan', 'jelmaan', 'pedoman',
    'khayalan', 'gejala', 'serabut', 'rumusan', 'gemintang', 'benteng',
    'gelagar', 'keturunan', 'kebumian', 'gerakan', 'ukuran', 'tingkatan',
    'hunian', 'marmut', 'serasi', 'kedap', 'silangan', 'sejarah',
    'getah', 'ibadah', 'haluan', 'impian', 'susuk', 'lumpuh',
    'temuan', 'pemasangan', 'sungsang', 'setara', 'jagat', 'jaminan',
    'jangkar', 'jejaring', 'raksasa', 'kacamata', 'hitungan', 'peserta',
    'modal', 'daftar', 'pemicu', 'kelamin', 'kerajaan', 'kesturi',
    'khasiat', 'kiblat', 'puncak', 'kumpulan', 'rumit', 'mufakat',
    'perjanjian', 'hablur', 'bobot', 'petugas', 'aliran', 'samping',
    'lawatan', 'lembaga', 'bebas', 'pasokan', 'besaran', 'mandiri',
    'ikrar', 'bahan', 'penengah', 'piring', 'memandu', 'menghibur',
    'raksa', 'cairan', 'tambang', 'rahasia', 'bagian', 'pantau',
    'tugu', 'negara', 'kemudi', 'kurang', 'nilai', 'biasa',
    'inti', 'tambun', 'cangkok', 'tanding', 'tindakan', 'terbaik',
    'hayati', 'gamelan', 'wewenang', 'padanan', 'palagan', 'pameran',
    'panitia', 'janggal', 'zarah', 'pejuang', 'pendidik', 'burung',
    'purna', 'senyawa', 'perangi', 'limas', 'tembaga', 'siasat',
    'jinjing', 'unggul', 'masalah', 'buatan', 'jabatan', 'gencar',
    'sebar', 'gizi', 'daerah', 'remaja', 'pusaran', 'tuntas',
    'rapuhnya', 'wadah', 'balas', 'satuan', 'relawan', 'ulangan',
    'pemulihan', 'perubahan', 'mesra', 'kubah', 'ilmiah', 'santunan',
    'sindiran', 'iringan', 'saksama', 'semangat', 'gempar', 'tengah',
    'tiruan', 'naskah', 'kokoh', 'pantulan', 'tahap', 'sebutan',
    'rencana', 'hakikat', 'untung', 'bingkisan', 'koran', 'cerdik',
    'dering', 'contoh', 'dalil', 'terbang', 'pangkalan', 'terang',
    'megah', 'bentuk', 'budaya', 'piagam', 'pengadilan', 'gelombang',
    'baling', 'peringatan', 'unggulan', 'manfaat', 'penangkal', 'hantu',
    'tumbuhan', 'lubang', 'maya', 'sari', 'sukarela', 'warisan',
    'takut', 'hukum', 'hewan',
  ],
  expert: [
    'menyimpang', 'pengampunan', 'penyesuaian', 'pembelaan', 'hambatan',
    'pengakuan', 'langkah', 'simpangan', 'kiasan', 'anggapan',
    'benda', 'antariksa', 'persiapan', 'kiamat', 'bangunan',
    'angkasa', 'pembuktian', 'sendiri', 'kehidupan', 'darah',
    'campuran', 'caturwulan', 'putaran', 'maklumat', 'demografi',
    'wicara', 'matra', 'hubungan', 'wacana', 'pembagian',
    'jaringan', 'pelaksana', 'percobaan', 'pemerasan', 'persamaan',
    'kamus', 'penyakit', 'tangga', 'penilai', 'berangsur',
    'pembuatan', 'penyedia', 'mendalam', 'mendasar', 'canggih',
    'kewilayahan', 'sejagat', 'tarikan', 'penyelarasan', 'belahan',
    'dugaan', 'melintang', 'pengenal', 'keyakinan', 'akibat',
    'petunjuk', 'prasarana', 'prakarsa', 'pembaru', 'gairah',
    'kejujuran', 'gangguan', 'penafsiran', 'penyelidikan', 'tetap',
    'peradilan', 'penaksiran', 'pemodal', 'tegas', 'keabadian',
    'keberanian', 'kebijakan', 'kecerdasan', 'keharmonisan', 'keistimewaan',
    'kekuasaan', 'kelaziman', 'kemandirian', 'kemiskinan', 'kemuliaan',
    'kenikmatan', 'kepastian', 'kepemimpinan', 'keragamaan', 'kerjasama',
    'kesehatan', 'ketahanan', 'ketimpangan', 'keunggulan', 'kerumitan',
    'bincang', 'pertemuan', 'pelestarian', 'kekinian', 'sumbangan',
    'penataan', 'rekaan', 'kejahatan', 'sifat', 'jumlah',
    'bengkel', 'landasan', 'pengesahan', 'merdeka', 'pustaka',
    'magistrat', 'perwujudan', 'rekayasa', 'penyetaraan', 'susunan',
    'sandiwara', 'pencernaan', 'pengkajian', 'ketentaraan', 'pembaruan',
    'monumental', 'kebinekaan', 'musyawarah', 'nasionalisme', 'navigasi',
    'penawaran', 'nonfiksi', 'penormalan', 'adil', 'pengamatan',
    'pojokan', 'persaingan', 'peluang', 'titik', 'perserikatan',
    'pengenalan', 'ajaran', 'bentang', 'bertentangan', 'partisipasi',
    'patologis', 'pengembangan', 'peradaban', 'kinerja',
    'perimbangan', 'berkala', 'kekal', 'pandang', 'pertimbangan',
    'penjiplakan', 'kemajemukan', 'negarawan', 'kemampuan', 'lugas',
    'pilihan', 'kemungkinan', 'terlatih', 'pesat', 'hasutan',
    'runtut', 'kebatinan', 'penyiaran', 'pemotretan', 'perbaikan',
    'nisbi', 'martabat', 'pemulihan', 'perombak', 'arti',
    'pemusatan', 'penting', 'peduli', 'keteraturan', 'pergaulan',
    'menakjubkan', 'mandek', 'pembakuan', 'data', 'kerangka',
    'berarti', 'kejayaan', 'penghubung', 'sementara', 'menyatu',
    'istilah', 'kedaerahan', 'kuno', 'peralihan', 'bening',
    'peringatan', 'perguruan', 'perpindahan', 'kegunaan', 'kesahihan',
    'pemeriksaan', 'pakar', 'penggambaran', 'pegunungan', 'kehakiman',
  ],
};

// ─── LANGUAGE-AWARE WORD BANK GETTER ─────────────────────────
export function getWordBanks(lang) {
  return lang === 'id' ? WORD_BANKS_ID : WORD_BANKS_EN;
}

export const UI_TEXT = {
  en: {
    score: 'SCORE',
    speed: 'SPEED',
    lvl: 'LVL',
    titleLine1: 'TYPING SPACE',
    titleLine2: 'SHOOTER',
    instruction1: 'Type the words above enemies to destroy them',
    instruction2: 'Collect Lucky Boxes for buffs & Hearts for HP',
    pressStart: '[ PRESS ENTER TO START ]',
    version: 'v1.1 — ENDLESS MODE',
    gameOver: 'GAME OVER',
    finalScore: 'FINAL SCORE',
    maxSpeed: 'MAX SPEED',
    level: 'LEVEL',
    pressRestart: '[ PRESS ENTER TO RESTART ]',
    hp: 'HP',
    buffSlowmo: 'SLOW MOTION',
    buffDouble: 'DOUBLE SCORE',
    buffBomb: 'BOMB!',
    buffShield: 'SHIELD',
    buffLaser: 'AUTO LASER',
    paused: 'GAME PAUSED',
    settings: 'SETTINGS',
    language: 'LANGUAGE',
    refreshRate: 'REFRESH RATE',
    musicVolume: 'MUSIC VOLUME',
    sfxVolume: 'SFX VOLUME',
    unlimited: 'UNLIMITED',
    pressEscResume: '[ PRESS ESC/ENTER TO RESUME ]',
    typeHere: '[ TYPE WORD HERE ]',
    resume: 'RESUME',
  },
  id: {
    score: 'SCORE',
    speed: 'SPEED',
    lvl: 'LVL',
    titleLine1: 'MENGETIK LUAR',
    titleLine2: 'ANGKASA',
    instruction1: 'Ketik kata di atas musuh untuk menghancurkannya',
    instruction2: 'Kumpulkan Kotak Buff & Hati untuk HP',
    pressStart: '[ TEKAN ENTER UNTUK MULAI ]',
    version: 'v1.1 — MODE TAK TERBATAS',
    gameOver: 'PERMAINAN BERAKHIR',
    finalScore: 'SKOR AKHIR',
    maxSpeed: 'KECEPATAN MAKS',
    level: 'LEVEL',
    pressRestart: '[ TEKAN ENTER UNTUK ULANG ]',
    hp: 'HP',
    buffSlowmo: 'GERAK LAMBAT',
    buffDouble: 'SKOR GANDA',
    buffBomb: 'BOM!',
    buffShield: 'PERISAI',
    buffLaser: 'LASER OTOMATIS',
    paused: 'PERMAINAN DIJEDA',
    settings: 'PENGATURAN',
    language: 'BAHASA',
    refreshRate: 'REFRESH RATE',
    musicVolume: 'VOLUME MUSIK',
    sfxVolume: 'VOLUME EFEK SUARA',
    unlimited: 'UNLIMITED',
    pressEscResume: '[ TEKAN ESC/ENTER UNTUK LANJUT ]',
    typeHere: '[ KETIK KATA DI SINI ]',
    resume: 'LANJUTKAN',
  },
};

// ─── GAME CONFIGURATION ─────────────────────────────────────
export const CONFIG = {
  PLAYER_DEFAULT_HEARTS: 3,
  PLAYER_MAX_HEARTS: 5,
  BASE_FALL_SPEED: 70,           // pixels per second
  BULLET_SPEED: 1100,            // pixels per second
  BASE_ALIEN_SPAWN_MS: 2800,     // milliseconds
  LUCKY_BOX_SPAWN_MS: 12000,
  HEART_SPAWN_MS: 18000,
  BUFF_DURATION_MS: 10000,
  SPEED_UP_INTERVAL: 75,         // every N points
  SPEED_UP_FACTOR: 1.08,         // multiplier per level
  SCORE_PER_ALIEN: 10,
  ENTITY_SIZE: 42,
  PLAYER_SIZE: 52,
  MAX_PARTICLES: 200,
  STAR_COUNT: 120,
};

// ─── BUFF DEFINITIONS ────────────────────────────────────────
export const BUFF_TYPES = [
  { id: 'slowmo', nameKey: 'buffSlowmo', color: '#00bfff' },
  { id: 'double', nameKey: 'buffDouble', color: '#ffd700' },
  { id: 'bomb', nameKey: 'buffBomb', color: '#ff4400', instant: true },
  { id: 'shield', nameKey: 'buffShield', color: '#00ff88', instant: true },
  { id: 'laser', nameKey: 'buffLaser', color: '#cc44ff' },
];
